#### Functions

In [ ]:
#Function
def square(x):
    y = x**3
    return x**2

def average(x,y):
    return (x+y)/2

#Function - as parameter
def useFunction(f, a,b):
    return f(a,b)

#useFunction(square, 3)
useFunction(average, 4,5)

In [ ]:
lst = range(10)
print(lst, lst[0], lst[9])

In [ ]:
#higher order Functions 
result = map(square, lst)
for i in result:
    print(i)

In [ ]:
type(result)

In [ ]:
import functools
result = functools.reduce(average, lst)
print(result)

In [ ]:
import numpy as np
result = np.mean(lst)
print(result)

#### Recursion

In [ ]:
def factorial(n):
    if n == 1:
        return 1
    else:
        return n*factorial(n-1)

print(factorial(9))
print(factorial(5))

#### Classes

In [1]:
class Account:
    accountID = 0
    name = 'noName'
    balance = 0
    
    def __init__(self, accountid=10, name=''):
        self.accountID = accountid
        self.name = name
        
    def deposit(self, amount=0):
        if amount < 0:
            raise ValueError("negative amount: $" + str(amount))
        self.balance += amount
    
    def detail(self):
        return self.accountID, self.name, self.balance

In [3]:
account = Account(23, "Kayne's Checking")

In [9]:
account.balance

300

In [6]:
x = account.deposit(100)

In [ ]:
type(x)

In [8]:
account.deposit(100)
print(account.detail())

try:
    account.deposit(-200)
except Exception as ex:
    print(ex)

(23, "Kayne's Checking", 300)
negative amount: $-200


In [19]:
class BankAccount(Account):
    type = 'Checking'
    
    def __init__(self, accountid=10, name='', accttype='Checking'):
        Account.__init__(self, accountid, name)
        self.type = accttype
    
    def deposit(self, amount=0):
        if amount < 0:
            raise ValueError("negative amount: $" + str(amount))
        self.balance += amount-5
        
    def withdraw(self, amount=0):
        if self.balance < 1000:
            raise ValueError("Minimun Balance $100 to be maintained, current Balance : $" + str(self.balance))
        self.balance -= amount
        return self.balance

In [20]:
myAccount = BankAccount(23, "Kayne's Checking")

In [21]:
myAccount.deposit(100)
print(myAccount.detail())
try:
    myAccount.withdraw(100)
except Exception as ex:
    print(ex)
    

(23, "Kayne's Checking", 95)
Minimun Balance $100 to be maintained, current Balance : $95


In [18]:
myAccount.deposit(10000)
try:
    myBalance = myAccount.withdraw(100)
    print(myBalance)
except Exception as ex:
    print(ex)

10000


#### Collections

In [23]:
# Tuples
# ordered, unchangeable, indexed, cannot add or remove items, allow duplicate values

x = ("apple", "banana","banana", "cherry")

In [26]:
x[2]='kiwi'

TypeError: 'tuple' object does not support item assignment

In [27]:
y = list(x)
y[1] = "kiwi"
x = tuple(y)
print(x[1])

kiwi


In [28]:
# Lists
# ordered, changeable, indexed, can add or remove items, allow duplicate values

fruits = ["apple", "banana", "banana", "cherry", "kiwi", "mango"]
newlist = [x for x in fruits if "a" in x]
print(newlist)

['apple', 'banana', 'banana', 'mango']


In [31]:
fruits.append('kiwi')
fruits
fruits[2]='guavava'
fruits

['apple',
 'banana',
 'guavava',
 'cherry',
 'kiwi',
 'mango',
 'kiwi',
 'kiwi',
 'kiwi']

In [32]:
# Sets
# unordered, unchangeable,unindexed, can add or remove items, do not allow duplicate values

thisset = {"apple", "banana",  "cherry", "banana"}
print(thisset)

{'banana', 'apple', 'cherry'}


In [33]:
#Dictionaries
# ordered, changeable, key-values, can add or remove items, and do not allow duplicates keys

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict['year'])
thisdict.update({"year": 2020})
print(thisdict['year'])

1964
2020


In [34]:


print(x)

('apple', 'kiwi', 'banana', 'cherry')


In [35]:
import numpy as np


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.sum()

78

In [43]:

newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:

asign = lambda t: 0 if t[:][:3].all()<5 else 1
A = list(map(asign, newarr))
print(A)

[0, 0, 0, 0]
